// flow-typed signature: d75906e04e173ae2f21dd4f053c9ea24
// flow-typed version: <<STUB>>/@pixi/jsdoc-template_v^2.4.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@pixi/jsdoc-template'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@pixi/jsdoc-template' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@pixi/jsdoc-template/plugins/es6-fix' {
  declare module.exports: any;
}

declare module '@pixi/jsdoc-template/publish' {
  declare module.exports: any;
}

declare module '@pixi/jsdoc-template/static/scripts/bootstrap.min' {
  declare module.exports: any;
}

declare module '@pixi/jsdoc-template/static/scripts/jquery.min' {
  declare module.exports: any;
}

declare module '@pixi/jsdoc-template/static/scripts/main' {
  declare module.exports: any;
}

declare module '@pixi/jsdoc-template/static/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module '@pixi/jsdoc-template/static/scripts/prettify/prettify' {
  declare module.exports: any;
}

// Filename aliases
declare module '@pixi/jsdoc-template/plugins/es6-fix.js' {
  declare module.exports: $Exports<'@pixi/jsdoc-template/plugins/es6-fix'>;
}
declare module '@pixi/jsdoc-template/publish.js' {
  declare module.exports: $Exports<'@pixi/jsdoc-template/publish'>;
}
declare module '@pixi/jsdoc-template/static/scripts/bootstrap.min.js' {
  declare module.exports: $Exports<'@pixi/jsdoc-template/static/scripts/bootstrap.min'>;
}
declare module '@pixi/jsdoc-template/static/scripts/jquery.min.js' {
  declare module.exports: $Exports<'@pixi/jsdoc-template/static/scripts/jquery.min'>;
}
declare module '@pixi/jsdoc-template/static/scripts/main.js' {
  declare module.exports: $Exports<'@pixi/jsdoc-template/static/scripts/main'>;
}
declare module '@pixi/jsdoc-template/static/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'@pixi/jsdoc-template/static/scripts/prettify/lang-css'>;
}
declare module '@pixi/jsdoc-template/static/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'@pixi/jsdoc-template/static/scripts/prettify/prettify'>;
}
