// flow-typed signature: e9e7c93cb92601374fa11807f97d07cc
// flow-typed version: <<STUB>>/component-webpack-resolver-plugin_v^2.0.2/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'component-webpack-resolver-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'component-webpack-resolver-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'component-webpack-resolver-plugin/lib/index' {
  declare module.exports: any;
}

declare module 'component-webpack-resolver-plugin/src/index' {
  declare module.exports: any;
}

declare module 'component-webpack-resolver-plugin/test/fixtures/BarComponent/BarComponent' {
  declare module.exports: any;
}

declare module 'component-webpack-resolver-plugin/test/fixtures/BarComponent/index' {
  declare module.exports: any;
}

declare module 'component-webpack-resolver-plugin/test/fixtures/FooComponent/FooComponent' {
  declare module.exports: any;
}

declare module 'component-webpack-resolver-plugin/test/index.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'component-webpack-resolver-plugin/lib/index.js' {
  declare module.exports: $Exports<'component-webpack-resolver-plugin/lib/index'>;
}
declare module 'component-webpack-resolver-plugin/src/index.js' {
  declare module.exports: $Exports<'component-webpack-resolver-plugin/src/index'>;
}
declare module 'component-webpack-resolver-plugin/test/fixtures/BarComponent/BarComponent.js' {
  declare module.exports: $Exports<'component-webpack-resolver-plugin/test/fixtures/BarComponent/BarComponent'>;
}
declare module 'component-webpack-resolver-plugin/test/fixtures/BarComponent/index.js' {
  declare module.exports: $Exports<'component-webpack-resolver-plugin/test/fixtures/BarComponent/index'>;
}
declare module 'component-webpack-resolver-plugin/test/fixtures/FooComponent/FooComponent.js' {
  declare module.exports: $Exports<'component-webpack-resolver-plugin/test/fixtures/FooComponent/FooComponent'>;
}
declare module 'component-webpack-resolver-plugin/test/index.spec.js' {
  declare module.exports: $Exports<'component-webpack-resolver-plugin/test/index.spec'>;
}
