// flow-typed signature: 35b757f27ac2b0d11f41b787d5c2f8ef
// flow-typed version: <<STUB>>/postcss-inline-media_v^1.0.1/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-inline-media'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-inline-media' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-inline-media/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-inline-media/index' {
  declare module.exports: $Exports<'postcss-inline-media'>;
}
declare module 'postcss-inline-media/index.js' {
  declare module.exports: $Exports<'postcss-inline-media'>;
}
declare module 'postcss-inline-media/test/test.js' {
  declare module.exports: $Exports<'postcss-inline-media/test/test'>;
}
