// flow-typed signature: 0b12cca15a0480e14cca67c7f1e19722
// flow-typed version: <<STUB>>/promise-map-es6_v^1.3.2/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'promise-map-es6'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'promise-map-es6' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'promise-map-es6/dist/promise-map' {
  declare module.exports: any;
}

declare module 'promise-map-es6/examples/aws-lambda-example' {
  declare module.exports: any;
}

declare module 'promise-map-es6/examples/fetch-example' {
  declare module.exports: any;
}

declare module 'promise-map-es6/examples/nested-fetch-example' {
  declare module.exports: any;
}

declare module 'promise-map-es6/lib/PromiseMap' {
  declare module.exports: any;
}

declare module 'promise-map-es6/webpack.config.babel' {
  declare module.exports: any;
}

// Filename aliases
declare module 'promise-map-es6/dist/promise-map.js' {
  declare module.exports: $Exports<'promise-map-es6/dist/promise-map'>;
}
declare module 'promise-map-es6/examples/aws-lambda-example.js' {
  declare module.exports: $Exports<'promise-map-es6/examples/aws-lambda-example'>;
}
declare module 'promise-map-es6/examples/fetch-example.js' {
  declare module.exports: $Exports<'promise-map-es6/examples/fetch-example'>;
}
declare module 'promise-map-es6/examples/nested-fetch-example.js' {
  declare module.exports: $Exports<'promise-map-es6/examples/nested-fetch-example'>;
}
declare module 'promise-map-es6/lib/PromiseMap.js' {
  declare module.exports: $Exports<'promise-map-es6/lib/PromiseMap'>;
}
declare module 'promise-map-es6/webpack.config.babel.js' {
  declare module.exports: $Exports<'promise-map-es6/webpack.config.babel'>;
}
