// flow-typed signature: 765f372827a4eb3edc445dfe56c4acb4
// flow-typed version: <<STUB>>/react-dev-tools_v^0.0.1/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dev-tools'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dev-tools' {
  declare module.exports: any;
}
