// flow-typed signature: 33d10fce78d85dc75ab019ee2d4ad449
// flow-typed version: <<STUB>>/reducer-generator-reducer_v^1.1.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reducer-generator-reducer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reducer-generator-reducer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reducer-generator-reducer/app' {
  declare module.exports: any;
}

declare module 'reducer-generator-reducer/dist/reducer-generator-reducer' {
  declare module.exports: any;
}

declare module 'reducer-generator-reducer/src/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reducer-generator-reducer/app.js' {
  declare module.exports: $Exports<'reducer-generator-reducer/app'>;
}
declare module 'reducer-generator-reducer/dist/reducer-generator-reducer.js' {
  declare module.exports: $Exports<'reducer-generator-reducer/dist/reducer-generator-reducer'>;
}
declare module 'reducer-generator-reducer/src/main.js' {
  declare module.exports: $Exports<'reducer-generator-reducer/src/main'>;
}
