// flow-typed signature: 442a02250ce082050c29301e0b29a820
// flow-typed version: <<STUB>>/reducer-generator-object-map_v^1.1.3/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reducer-generator-object-map'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reducer-generator-object-map' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reducer-generator-object-map/app' {
  declare module.exports: any;
}

declare module 'reducer-generator-object-map/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'reducer-generator-object-map/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'reducer-generator-object-map/dist/reducer-generator-object-map' {
  declare module.exports: any;
}

declare module 'reducer-generator-object-map/src/main' {
  declare module.exports: any;
}

declare module 'reducer-generator-object-map/test/setup' {
  declare module.exports: any;
}

declare module 'reducer-generator-object-map/test/tests/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reducer-generator-object-map/app.js' {
  declare module.exports: $Exports<'reducer-generator-object-map/app'>;
}
declare module 'reducer-generator-object-map/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'reducer-generator-object-map/coverage/lcov-report/prettify'>;
}
declare module 'reducer-generator-object-map/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'reducer-generator-object-map/coverage/lcov-report/sorter'>;
}
declare module 'reducer-generator-object-map/dist/reducer-generator-object-map.js' {
  declare module.exports: $Exports<'reducer-generator-object-map/dist/reducer-generator-object-map'>;
}
declare module 'reducer-generator-object-map/src/main.js' {
  declare module.exports: $Exports<'reducer-generator-object-map/src/main'>;
}
declare module 'reducer-generator-object-map/test/setup.js' {
  declare module.exports: $Exports<'reducer-generator-object-map/test/setup'>;
}
declare module 'reducer-generator-object-map/test/tests/main.js' {
  declare module.exports: $Exports<'reducer-generator-object-map/test/tests/main'>;
}
