// flow-typed signature: cac1555af8ba42f0d67aa69cbec68f03
// flow-typed version: <<STUB>>/reducer-generator-wildcard_v^1.1.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reducer-generator-wildcard'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reducer-generator-wildcard' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reducer-generator-wildcard/app' {
  declare module.exports: any;
}

declare module 'reducer-generator-wildcard/dist/reducer-generator-wildcard' {
  declare module.exports: any;
}

declare module 'reducer-generator-wildcard/src/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reducer-generator-wildcard/app.js' {
  declare module.exports: $Exports<'reducer-generator-wildcard/app'>;
}
declare module 'reducer-generator-wildcard/dist/reducer-generator-wildcard.js' {
  declare module.exports: $Exports<'reducer-generator-wildcard/dist/reducer-generator-wildcard'>;
}
declare module 'reducer-generator-wildcard/src/main.js' {
  declare module.exports: $Exports<'reducer-generator-wildcard/src/main'>;
}
