// flow-typed signature: cf700224899dd2bec4a13fd5ae62c870
// flow-typed version: <<STUB>>/reducer-generator-array-map_v^1.1.2/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reducer-generator-array-map'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reducer-generator-array-map' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reducer-generator-array-map/app' {
  declare module.exports: any;
}

declare module 'reducer-generator-array-map/dist/reducer-generator-array-map' {
  declare module.exports: any;
}

declare module 'reducer-generator-array-map/src/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reducer-generator-array-map/app.js' {
  declare module.exports: $Exports<'reducer-generator-array-map/app'>;
}
declare module 'reducer-generator-array-map/dist/reducer-generator-array-map.js' {
  declare module.exports: $Exports<'reducer-generator-array-map/dist/reducer-generator-array-map'>;
}
declare module 'reducer-generator-array-map/src/main.js' {
  declare module.exports: $Exports<'reducer-generator-array-map/src/main'>;
}
