// flow-typed signature: c26b385071baf127291dd23abcaf0dea
// flow-typed version: <<STUB>>/set-queue_v^1.0.6/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'set-queue'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'set-queue' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'set-queue/app' {
  declare module.exports: any;
}

declare module 'set-queue/dist/set-queue' {
  declare module.exports: any;
}

declare module 'set-queue/src/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'set-queue/app.js' {
  declare module.exports: $Exports<'set-queue/app'>;
}
declare module 'set-queue/dist/set-queue.js' {
  declare module.exports: $Exports<'set-queue/dist/set-queue'>;
}
declare module 'set-queue/src/main.js' {
  declare module.exports: $Exports<'set-queue/src/main'>;
}
