// flow-typed signature: 4ad750f5a0f1d5bdccf69561dd714750
// flow-typed version: <<STUB>>/@babel/plugin-codemod-optional-catch-binding_v^7.0.0-beta.46/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-codemod-optional-catch-binding'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-codemod-optional-catch-binding' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-codemod-optional-catch-binding/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-codemod-optional-catch-binding/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-codemod-optional-catch-binding/lib/index'>;
}
